### ISSUE TITLE
1.0 Invenia wish list

### ISSUE THREAD

**Issue by andrewrosemberg** [NREL-SIIP/PowerSimulations.jl#524]
Upcoming with the update to PSY 1.0
- [x] Cost refactor (https://github.com/NREL-SIIP/PowerSimulations.jl/pull/516, #514)
- [x] `ThemalStandard` parameters Forecasts (mainly Pmax and Pmin)
- [x] Cost forecast (maybe it's already in the cost refactor, mark as done if so)
- [ ] Functions and types exports (https://github.com/NREL-SIIP/PowerSimulations.jl/issues/520)
- [ ] Non-spinning reserves (https://github.com/NREL-SIIP/PowerSimulations.jl/issues/478)
- [ ] Bidding Loads (https://github.com/NREL-SIIP/PowerSystems.jl/issues/606)
- [ ] Forecasts for `unit availability` and `must run` flag. (https://github.com/NREL-SIIP/PowerSystems.jl/issues/790)
- [ ] Forecasts for service `contributing_devices`. (https://github.com/NREL-SIIP/PowerSystems.jl/issues/790)

Edit note: @jd-lara modified the comment to give some expected timelines to the feature requests

**Comment by raphaelsaavedra** [comment]
> Functions and types exports (#520)

For this topic, note that there are two distinct related issues. 

One is that several functions that are useful to type II users are unexported and we think some should be exported.

The other is that any dispatch on `construct_device` requires a PowerModels dependency because of `AbstractActivePowerModel`. It would be useful to have this PowerModels type (and possibly others) exported by PowerSystems.

**Comment by andrewrosemberg** [comment]
I added bidding loads since it's also something that is very much needed, and, as we discussed, is not covered by interruptible loads.

@jd-lara if this is already covered by the cost refactor, please let me know.

**Comment by jd-lara** [comment]
@andrewrosemberg we need a new load in PowerSystems.jl too. @claytonpbarrows has more information about the upcoming DR loads.

**Comment by jd-lara** [comment]
I am closing this issue since the list has been already split to the respective packages where they apply.
